name: pro_calendar
description: قالب تقويم احترافي لإدارة الأيام والأحداث والمهام محليًا.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
